### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by zois1** [MikeSiLVO/Aeon-Nox-SiLVO#158]
I can no longer adjust colors in customize skin. Do I have to remove silvo nox or is there another solution

**Comment by jewbmx** [comment]
If you spot this post @mikesilvo164 , i thought id leave it here since it is probably the same thing or atleast similar lol.

When trying to change colors in kodi v20 a error happens with colorpicker in its named .py file on line 15 because of the translatePath changes. Instead of xbmc its now xbmcvfs.

Also request the idea to add in more preset options like basic colors of the rainbow that way we can still have a nice variety if the colorpicker addon ever breaks again lol.

**Comment by MikeSiLVO** [comment]
I added Nexus color picker support so an add-on is no longer required to change skin colors.
I will also try to add more preset color options if I can find some good complimentary color designs.
4179c8e
